# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: genset 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "genset".freeze
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jason Ihaia".freeze]
  s.date = "2016-10-29"
  s.description = "Longer description of your gem".freeze
  s.email = "jason@ihaia.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "genset.gemspec",
    "lib/genset.rb"
  ]
  s.homepage = "https://genset.github.com/genset".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.4".freeze
  s.summary = "One-line summary of your gem".freeze

  
end
